### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by kouwei32** [bigratmonster/bigrat.monster#52]
This repository currently has no license. Others currently only have the [legal rights to view and fork the source code](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license) via Github's Terms of Service. Consider adding an open source license perhaps? The [MIT License](https://choosealicense.com/licenses/mit/) or the [Unlicense](https://choosealicense.com/licenses/unlicense/) may do well here, though some others like the [GPLv3](https://choosealicense.com/licenses/gpl-3.0/) may be more suitable if you wish for derivative works to remain free.

Note that this specific repository has caveats; many (if not all) of the image assets that it utilizes are unclear in original author and licensing. They should not be included under a license as they are not original works. Consider placing them in a different root folder and/or adding a standalone disclaimer if possible.

**Comment by SoNothingMC** [comment]
> Note that this specific repository has caveats; many (if not all) of the image assets that it utilizes are unclear in original author and licensing.

Currently, all media assets are already placed under /media (and has been since Aug 2020, d569ddadd27e581249ae79a1892be80cf6393cd3)

---

I've been thinking about whether we should license bigrat.monster from the first commit, and eventually decided to just leave it as All Rights Reserved and just let people do things under GitHub ToS. I'm just a random teenager who is pretty scared of copyrights in general and wanted to take a safer bet (and not release some other people's work under an OSS license).

If we were to add a license for bigrat.monster, in typical SoNothing fashion it'll be [WTFPL](http://www.wtfpl.net) (which is as non-serious as this repository itself), but I think Unlicense would be a better, less-cuss-worded alternative for this repository. (If other people has any thoughts on this please drop in!)

Also, there's this issue of the process taking super long to finish.  
I'm not a lawyer (pls no sue), but I've heard that all the contributors of the repository need to accept the license change in order for us to actually apply a license into the repository.  
Since bigrat.monster is really not in its full popularity anymore following the Discord server's shutdown (more on that in this old [README](https://github.com/bigratmonster/bigrat.monster/blob/96b5f819c9c7ed6c858f71fc6d70b9985f3fd9cc/readme.md)), I think it'd take a looooooong time for all contributors (some are inactive) for the repository to actually get licensed. This may seem like a non-issue but copyright-related stuffs really take a mental toll on me... (so maybe we should do it now - better late then never?)

¯\\_\(ツ\)\_\/¯
