### ISSUE TITLE
Stop using the discord CDN

### ISSUE THREAD

**Issue by l-koehler** [bigratmonster/bigrat.monster#78]
**Describe the bug**
bigrat.monster/quiz currently loads content using a link to the discord CDN. This is bound to stop working eventually.

**To Reproduce**
Look at [Line 21 in /js/quiz.js](https://github.com/bigratmonster/bigrat.monster/blob/7b27be3db984434c98eba4d49da736cd20ebb62b/js/quiz.js#L21), it loads the following image:
https://cdn.discordapp.com/attachments/689287762335367255/775898066074992650/s7f1gobxlkm51.jpg.

**Expected behavior**
Not loading content from cdn.discordapp.com, but instead from https://bigrat.monster/media/

**Additional context**
Discord started timestamping these CDN links, so it is likely that the non-timestamped links will be invalid soon.
See https://reddit.com/r/DataHoarder/comments/16zs1gt/cdndiscordapp_links_will_expire_breaking/ for additional info.

**Comment by SoNothingMC** [comment]
Thank you for your advice.  
As part of the cleanup actions described in https://github.com/bigratmonster/bigrat.monster/discussions/72#discussioncomment-6865945, Bigrat Quiz will be removed soon.

However, I'll implement a temporary fix in the next day and a half because it will take a while for me finish the cleanup (due to IRL issues).

Again, thank you for reminding me, I totally forgot we have Discord CDN links included within quiz.js.
